# -*- coding: utf-8 -*-
"""Client.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QThvcUwXPFCWJaBJYteTFdsJAKRyTzYo
"""

import socket

def main():
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_address = ('localhost', 7501)

    try:
        client_socket.connect(server_address)
        user_input = input("Enter a string: ")
        client_socket.sendall(user_input.encode())
        response = client_socket.recv(1024)
        print("Server response:", response.decode())

    finally:
        client_socket.close()

if __name__ == "__main__":
    main()